### PR TITLE
Nested use path

### LINKED ISSUE #50: Problems with navigation and nested routes
Hi, I've found some strange problems with navigation when you are using nested routes with params. I'm testing with the latest version 1.4.

## How to reproduce?
Here is the link to the reproduction code:
https://stackblitz.com/edit/react-raviger-test?file=index.js

Press on the links in the bottom part in that order to:
1. nested with a param About (the route is loaded)
2. nested with a param Test (the route is **not** loaded)
3. root (the route is loaded)
4. nested with a param Test (the route is loaded)
5. root (the route is loaded)
6. nested with a param Test (the route is loaded)
7. nested with a param About (the route is **not** loaded)

raviger-bug

## Possible cause
I've checked many things, and I think the `useLocationChange` hook is the main suspect. It looks like [the if condition with `inheritBasePath` option](https://github.com/kyeotic/raviger/blob/1e7992cf08fafd6ac7429197a2b08bdbd450d9ad/src/path.js#L51) is causing the problem. I haven't found any other place where this option is used internally.

I was trying to debug the code with breakpoints in browser devtools. After setting the value of `basePath` to what is provided with `options` the issue is gone:
inheritBasePath-hack
raviger-fixed

Do you reckon we could somehow fix this behaviour? Maybe we just need to remove the `inheritBasePath` condition 😄 or force the `false` value when using hook internally from the `useRoutes` hook?

### PR DESCRIPTION
**Pull request by kyeotic**
This should fix #50 

I tried to verify this, but I don't have time to fully vet it tonight but I want to unblock @macku so I am publishing under the `beta` tag

```
npm i raviger@beta
OR
npm i raviger@1.4.1-0
```

I will vet tomorrow and release on proper if it looks good.

### CODE REVIEW

File: src/path.js [hunk 1]
```diff
@@ -7,7 +7,8 @@ export function usePath(basePath) {
   let contextBasePath = useBasePath() // hooks can't be called conditionally
   basePath = basePath || contextBasePath
   let [path, setPath] = useState(getCurrentPath(basePath))
-  useLocationChange(setPath, { basePath })
+  // useLocationChange(setPath, { basePath })
+  useLocationChange(setPath, { basePath, inheritBasePath: !basePath })
```
Comment (macku) [inline src/path.js:11]: I can confirm that this change works as expected!
